apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gitops-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gitops-service
    app.kubernetes.io/part-of: try-out-appstudio-build
  name: gitops-service
  namespace: shbose
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gitops-service
    weight: 100
status: {}
