apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    build.appstudio.openshift.io/application: try-out-appstudio-build
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: spi-oauth-service
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: spi-oauth-service
  namespace: shbose
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: spi-oauth-service
status:
  configuration:
    generatedName: ""
