apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: spi-oauth-service
  namespace: shbose
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: try-out-appstudio-build
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: spi-oauth-service
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: spi-oauth-service-
      labels:
        build.appstudio.openshift.io/application: try-out-appstudio-build
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: spi-oauth-service
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: shbose
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio/service-provider-integration-oauth
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:shbose-spi-oauth-service-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: spi-oauth-service/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
